### PR TITLE
Render a HEA query in Optimade.Science

### PR DESCRIPTION
**Pull request by blokhin**
Hi, I believe, this adds some additional value for a reader.

### CODE REVIEW

**Comment by ml-evs** [comment]
Thanks @blokhin, this is useful! Before merging, has any progress been made on https://github.com/tilde-lab/optimade.science/issues/54? It looks like this breaks the response from odbx and Materials Cloud atm. I think perhaps the providers list you use could also be updated to include the latest databases.

**Comment by blokhin** [comment]
@ml-evs please, merge :pray:

**Comment by ml-evs** [comment]
Hi @blokhin, thanks for your efforts updating optimade.science, will merge! Hopefully those providers where this query is still broken (AFLOW, NOMAD etc.) will fix it in time.

**Comment by ml-evs** [comment]
Also @blokhin FYI, the MPDS OPTIMADE API pagination links are not correct, they are currently provided as `links->next_page` rather than `links->next` so do not work with any of the Python-based clients (that I know of)

**Pull request merged**
